@echo off
REM Semgrep Security Audit Script for Windows
REM Usage: run-semgrep-audit.bat [security|quality|full|custom]

setlocal enabledelayedexpansion

set SCRIPT_DIR=%~dp0
set REPORT_DIR=%SCRIPT_DIR%audit-reports
set TIMESTAMP=%date:~-4,4%%date:~-10,2%%date:~-7,2%_%time:~0,2%%time:~3,2%%time:~6,2%
set TIMESTAMP=%TIMESTAMP: =0%

REM Create reports directory
if not exist "%REPORT_DIR%" mkdir "%REPORT_DIR%"

echo ====================================
echo Semgrep Security Audit Tool
echo ====================================
echo Report directory: %REPORT_DIR%
echo Timestamp: %TIMESTAMP%
echo.

REM Check if semgrep is installed
where semgrep >nul 2>nul
if %errorlevel% neq 0 (
    echo ERROR: Semgrep not found. Please install it first:
    echo pip install semgrep
    exit /b 1
)

REM Main execution logic
set SCAN_TYPE=%1
if "%SCAN_TYPE%"=="security" (
    goto security_audit
)
if "%SCAN_TYPE%"=="quality" (
    goto quality_audit
)
if "%SCAN_TYPE%"=="full" (
    goto full_audit
)
if "%SCAN_TYPE%"=="custom" (
    goto custom_audit
)
if "%SCAN_TYPE%"=="" (
    goto full_audit
)

echo Usage: %0 [security^|quality^|full^|custom]
echo.
echo Options:
echo   security  - Run security-focused audit
echo   quality   - Run code quality audit
echo   full      - Run comprehensive audit (default)
echo   custom    - Run custom configuration
echo.
echo Examples:
echo   %0 security
echo   %0 full
echo   %0 custom "p/secrets,p/sql-injection"
exit /b 1

:security_audit
echo Running Security-Focused Audit...
echo.

set CONFIG=p/security-audit,p/secrets,p/sql-injection,p/command-injection,p/xss
set OUTPUT_FILE=%REPORT_DIR%\security-audit_%TIMESTAMP%.json

echo Running: Security Rules (OWASP Top 10, Secrets, Injection)
semgrep --config="%CONFIG%" --json --output="%OUTPUT_FILE%" .

if %errorlevel% equ 0 (
    echo ✅ Scan completed successfully
    echo 📊 Report saved to: %OUTPUT_FILE%
) else (
    echo ❌ Scan failed
    exit /b 1
)

goto end

:quality_audit
echo Running Code Quality Audit...
echo.

set CONFIG=p/bandit,p/flask,p/django
set OUTPUT_FILE=%REPORT_DIR%\quality-audit_%TIMESTAMP%.json

echo Running: Code Quality Rules (Bandit, Flask, Django)
semgrep --config="%CONFIG%" --json --output="%OUTPUT_FILE%" .

if %errorlevel% equ 0 (
    echo ✅ Scan completed successfully
    echo 📊 Report saved to: %OUTPUT_FILE%
) else (
    echo ❌ Scan failed
    exit /b 1
)

goto end

:full_audit
echo Running Comprehensive Full Audit...
echo.

REM Security scan
set CONFIG=p/security-audit,p/secrets,p/sql-injection,p/command-injection,p/xss
set OUTPUT_FILE=%REPORT_DIR%\security_%TIMESTAMP%.json

echo Running: Security Rules
semgrep --config="%CONFIG%" --json --output="%OUTPUT_FILE%" .

if %errorlevel% equ 0 (
    echo ✅ Security scan completed
) else (
    echo ⚠️ Security scan had issues
)

REM Python security scan
set CONFIG=p/bandit,p/flask,p/django,p/sql-injection
set OUTPUT_FILE2=%REPORT_DIR%\python-security_%TIMESTAMP%.json

echo Running: Python Security Rules
semgrep --config="%CONFIG%" --json --output="%OUTPUT_FILE2%" .

if %errorlevel% equ 0 (
    echo ✅ Python security scan completed
) else (
    echo ⚠️ Python security scan had issues
)

REM Create summary
echo Creating summary report...
set SUMMARY_FILE=%REPORT_DIR%\summary_%TIMESTAMP%.md

echo # Semgrep Audit Summary > "%SUMMARY_FILE%"
echo. >> "%SUMMARY_FILE%"
echo **Timestamp:** %date% %time% >> "%SUMMARY_FILE%"
echo **Scan Type:** Full Comprehensive Audit >> "%SUMMARY_FILE%"
echo. >> "%SUMMARY_FILE%"
echo ## Reports Generated >> "%SUMMARY_FILE%"
echo - Security JSON Data: security_%TIMESTAMP%.json >> "%SUMMARY_FILE%"
echo - Python Security JSON Data: python-security_%TIMESTAMP%.json >> "%SUMMARY_FILE%"
echo. >> "%SUMMARY_FILE%"
echo ## Quick Actions >> "%SUMMARY_FILE%"
echo 1. Review high-severity findings first >> "%SUMMARY_FILE%"
echo 2. Address security vulnerabilities immediately >> "%SUMMARY_FILE%"
echo 3. Create tickets for medium/low priority issues >> "%SUMMARY_FILE%"
echo 4. Update code to prevent future occurrences >> "%SUMMARY_FILE%"
echo. >> "%SUMMARY_FILE%"
echo --- >> "%SUMMARY_FILE%"
echo *Generated by Semgrep Audit Script* >> "%SUMMARY_FILE%"

echo ✅ Full audit completed!
echo 📊 Summary report: %SUMMARY_FILE%
echo 📁 All reports saved to: %REPORT_DIR%

goto end

:custom_audit
if "%2"=="" (
    echo ERROR: Custom scan requires configuration argument
    echo Usage: %0 custom "p/security-audit,p/bandit"
    exit /b 1
)

echo Running Custom Audit...
echo.

set CONFIG=%2
set OUTPUT_FILE=%REPORT_DIR%\custom-audit_%TIMESTAMP%.json

echo Running: Custom Configuration - %CONFIG%
semgrep --config="%CONFIG%" --json --output="%OUTPUT_FILE%" .

if %errorlevel% equ 0 (
    echo ✅ Custom audit completed
    echo 📊 Report saved to: %OUTPUT_FILE%
) else (
    echo ❌ Custom audit failed
    exit /b 1
)

goto end

:end
echo.
echo ====================================
echo Audit Complete
echo ====================================
echo ✅ All reports saved to: %REPORT_DIR%
echo.
echo Latest Reports:
dir /b "%REPORT_DIR%\*%TIMESTAMP%*" 2>nul
echo.
echo To view JSON reports, use a JSON viewer or:
echo type "%REPORT_DIR%\security_%TIMESTAMP%.json" | findstr /C:"check_id"
echo.
echo For detailed analysis, open the JSON files in a code editor or use jq if available.
pause
