-- Security Hardening based on Linter Findings
-- Generated by Antigravity

-- =================================================================
-- 1. Exposed Auth Users
-- =================================================================
-- Revoke access to views exposing auth.users to anon/authenticated
REVOKE ALL ON public.mv_conversion_funnel FROM anon, authenticated;
REVOKE ALL ON public.mv_weekly_cohorts FROM anon, authenticated;

-- =================================================================
-- 2. Security Definer Views
-- =================================================================
-- Convert views to Security Invoker to enforce RLS of the caller
-- (Requires Postgres 15+)
ALTER VIEW public.task_events SET (security_invoker = true);
ALTER VIEW public.target_forms SET (security_invoker = true);
ALTER VIEW public.task_inputs SET (security_invoker = true);
ALTER VIEW public.tasks SET (security_invoker = true);

-- =================================================================
-- 3. Missing RLS
-- =================================================================
-- Enable Row Level Security (Default Deny) on public tables
ALTER TABLE public.user_properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experiments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experiment_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.email_digest_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grant_portals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.author_payouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enterprise_onboarding ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.university_partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.university_student_imports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contract_renewals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platform_telemetry ENABLE ROW LEVEL SECURITY;
