import React from 'react';
import { useParams, Link } from 'react-router-dom';
import { Bot, ArrowLeft, BookOpen, Clock, Calendar, Share2, ChevronRight, Zap, Shield, Target } from 'lucide-react';
import { SEO } from '../components/marketing/SEO';
import { motion } from 'framer-motion';

const GUIDE_CONTENT: Record<string, any> = {
  'how-to-beat-ats-with-ai': {
    title: 'How to Beat ATS with AI Agents',
    category: 'Strategy',
    readTime: '8 min',
    content: `
      <h3>The Reality of Modern Recruitment</h3>
      <p>Applicant Tracking Systems (ATS) were designed to filter out noise, but in 2026, they often filter out quality. To beat them, you need to understand their logic. Our AI agents don't just "keyword stuff"—they model the semantic intent behind job descriptions.</p>
      
      <h3>1. Semantic Mapping vs. Keyword Matching</h3>
      <p>Legacy systems looked for exact strings. Modern ATS use vector embeddings to find similar concepts. JobHuntin uses a similar architecture to ensure your experience is mapped correctly to the recruiter's internal model.</p>
      
      <h3>2. The "Human-in-the-Loop" Fallacy</h3>
      <p>Many job seekers believe a human will eventually see their PDF. In reality, a human only sees a "Score Card" generated by an AI. Our agent optimizes for that score card while maintaining a tone that sounds human to the eventual human reviewer.</p>
    `
  },
  'automated-job-search-ethics': {
    title: 'The Ethics of Automated Job Hunting',
    category: 'Ethics',
    readTime: '12 min',
    content: `
      <h3>Efficiency is Not a Crime</h3>
      <p>Is it "cheating" to use an AI to apply? We argue that it is the only way to maintain parity in an environment where companies use AI to filter. This guide explores the ethical boundaries of automation.</p>
      
      <h3>1. Transparency and Intent</h3>
      <p>We believe automation should be used to facilitate discovery, not to deceive. Our agents represent you truthfully, using your real data and verified skills.</p>
      
      <h3>2. The Future of Work</h3>
      <p>As agents become more common, the nature of the application will change from a static document to a verified interaction history. JobHuntin is at the forefront of this shift.</p>
    `
  },
  'scaling-your-applications-safely': {
    title: 'Scaling Your Applications Safely',
    category: 'Safety',
    readTime: '10 min',
    content: `
      <h3>Quality vs. Quantity</h3>
      <p>The biggest mistake in job hunting is sending generic applications to 100s of roles. This is a fast track to getting blacklisted. Our safety protocol ensures every application is unique and high-quality.</p>
      
      <h3>1. Rate Limiting and Human Patterns</h3>
      <p>Applying to 50 jobs in 5 minutes is a clear bot signal. JobHuntin simulates human browsing patterns—varying the time between clicks and only applying when it's "safe."</p>
      
      <h3>2. IP and Browser Fingerprinting</h3>
      <p>Modern job boards track your device. Our extension-based approach ensures applications come from your verified IP, maintaining the trust score of your profile.</p>
    `
  },
  'ai-cover-letter-mastery': {
    title: 'AI Cover Letter Mastery',
    category: 'Tips',
    readTime: '6 min',
    content: `
      <h3>The End of the Template</h3>
      <p>Recruiters can spot a generic AI cover letter from a mile away. To stand out, you need specific tailoring that connects your unique history to the company's current challenges.</p>
      
      <h3>1. The "Connection" Prompt</h3>
      <p>Instead of "Write a cover letter for X role," we use prompts that analyze the company's recent news, funding, or product launches and tie them to your specific skill set.</p>
      
      <h3>2. Less is More</h3>
      <p>A great cover letter is short, punchy, and provides a clear call to action. Our AI is trained to avoid fluff and focus on value.</p>
    `
  }
};

export default function GuidePage() {
  const { guideSlug } = useParams<{ guideSlug: string }>();
  const guide = guideSlug ? GUIDE_CONTENT[guideSlug] : null;

  if (!guide) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center p-6 text-center bg-slate-50">
        <BookOpen className="w-16 h-16 text-primary-500 mb-4 animate-pulse" />
        <h1 className="text-2xl font-bold mb-4 text-slate-900">Guide Not Found</h1>
        <Link to="/guides" className="text-primary-600 hover:underline flex items-center gap-2 font-medium">
          <ArrowLeft className="w-4 h-4" /> Back to Playbook
        </Link>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 font-sans text-slate-900 selection:bg-primary-500/20 selection:text-primary-700">
      <SEO 
        title={`${guide.title} | JobHuntin Playbook`}
        description={`Deep dive into ${guide.title.toLowerCase()}. Part of the JobHuntin AI automation playbook.`}
        ogTitle={`${guide.title} | JobHuntin Playbook`}
        ogImage={`https://sorce-web.onrender.com/api/og?job=${encodeURIComponent(guide.title)}&company=JobHuntin&score=100&location=Global`}
        canonicalUrl={`https://jobhuntin.com/guides/${guideSlug}`}
        schema={{
          "@context": "https://schema.org",
          "@type": "Article",
          "headline": guide.title,
          "description": `Deep dive into ${guide.title.toLowerCase()}. Part of the JobHuntin AI automation playbook.`,
          "url": `https://jobhuntin.com/guides/${guideSlug}`,
          "about": guide.category
        }}
      />
      
      <nav className="px-6 py-4 bg-white/80 backdrop-blur-md sticky top-0 z-50 border-b border-gray-100">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <Link to="/guides" className="flex items-center gap-2">
            <div className="bg-gradient-to-tr from-primary-500 to-primary-600 p-2 rounded-xl rotate-3 shadow-lg shadow-primary-500/20">
              <Bot className="text-white w-6 h-6" />
            </div>
            <span className="text-xl font-bold font-display text-slate-900">JobHuntin <span className="text-slate-400 font-normal">Playbook</span></span>
          </Link>
          <Link to="/guides" className="text-sm font-medium text-slate-600 hover:text-primary-600 flex items-center gap-2 group transition-colors">
            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" /> Back to Guides
          </Link>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 py-20">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-12"
        >
          <div className="flex items-center gap-4 text-sm text-slate-400 font-bold uppercase tracking-widest mb-6">
            <span className="text-primary-500">{guide.category}</span>
            <span className="w-1 h-1 bg-slate-300 rounded-full" />
            <div className="flex items-center gap-2">
              <Clock className="w-4 h-4" /> {guide.readTime}
            </div>
          </div>
          <h1 className="text-4xl md:text-6xl font-black font-display mb-8 leading-tight text-slate-900">
            {guide.title}
          </h1>
          <div className="flex items-center justify-between border-y border-slate-200 py-6">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-slate-900 rounded-full flex items-center justify-center text-white font-bold text-xs">JH</div>
              <div>
                <p className="text-sm font-bold text-slate-900">JobHuntin Research Team</p>
                <p className="text-xs text-slate-500">Updated Feb 8, 2026</p>
              </div>
            </div>
            <button className="p-2 hover:bg-slate-100 rounded-full transition-colors text-slate-400 hover:text-slate-900">
              <Share2 className="w-5 h-5" />
            </button>
          </div>
        </motion.div>

        <article 
          className="prose prose-lg max-w-none prose-headings:font-display prose-headings:font-bold prose-headings:text-slate-900 prose-p:text-slate-600 prose-a:text-primary-600 mb-20 prose-strong:text-slate-900"
          dangerouslySetInnerHTML={{ __html: guide.content }}
        />

        <div className="bg-white rounded-[2.5rem] p-10 border border-slate-100 shadow-sm mb-20">
          <h3 className="text-2xl font-bold mb-6 font-display text-slate-900">Related Tools</h3>
          <div className="grid sm:grid-cols-2 gap-4">
            <Link to="/chrome-extension" className="flex items-center gap-4 p-4 rounded-2xl hover:bg-slate-50 transition-colors border border-transparent hover:border-slate-100 group">
              <div className="w-12 h-12 bg-orange-50 text-primary-500 rounded-xl flex items-center justify-center flex-shrink-0 group-hover:bg-primary-500 group-hover:text-white transition-colors">
                <Zap className="w-6 h-6" />
              </div>
              <div>
                <p className="font-bold text-sm text-slate-900">Chrome Extension</p>
                <p className="text-xs text-slate-400">Auto-apply while browsing</p>
              </div>
            </Link>
            <Link to="/pricing" className="flex items-center gap-4 p-4 rounded-2xl hover:bg-slate-50 transition-colors border border-transparent hover:border-slate-100 group">
              <div className="w-12 h-12 bg-blue-50 text-blue-500 rounded-xl flex items-center justify-center flex-shrink-0 group-hover:bg-blue-500 group-hover:text-white transition-colors">
                <Target className="w-6 h-6" />
              </div>
              <div>
                <p className="font-bold text-sm text-slate-900">Pro Hunter Plan</p>
                <p className="text-xs text-slate-400">Scale your hunt 10x</p>
              </div>
            </Link>
          </div>
        </div>

        <div className="bg-slate-900 rounded-[3rem] p-12 text-white text-center relative overflow-hidden shadow-2xl">
          <div className="absolute top-0 left-0 w-full h-full bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-10" />
          <h2 className="text-3xl font-bold mb-6 relative z-10 font-display">Experience the automation.</h2>
          <p className="text-slate-400 mb-10 relative z-10 max-w-lg mx-auto text-lg">
            Ready to put these strategies into practice? Let our agent handle your next 50 applications.
          </p>
          <Link 
            to="/login" 
            className="inline-block bg-primary-600 hover:bg-primary-700 text-white px-10 py-4 rounded-2xl font-bold text-lg hover:scale-105 transition-transform shadow-xl shadow-primary-500/20"
          >
            Start Your Run
          </Link>
        </div>
      </main>

      <footer className="bg-white border-t border-slate-200 py-12 mt-20">
        <div className="max-w-7xl mx-auto px-6 text-center text-slate-400 text-sm font-medium">
          &copy; {new Date().getFullYear()} JobHuntin AI. All rights reserved.
        </div>
      </footer>
    </div>
  );
}
